#lang racket

(require racket/list/grouping)

#|

Convert a sudoko problem to CNF and output in DIMACS format.

|#

;; Template for puzzles. Anything by "." or a digit is ignored.
; ...|...|...
; ...|...|...
; ...|...|...
; ---|---|---
; ...|...|...
; ...|...|...
; ...|...|...
; ---|---|---
; ...|...|...
; ...|...|...
; ...|...|...

;; The literal 81 * row + 9 * col + digit + 1 is a proposition
;; indicating that digit is in row and col. The negative of this
;; number indicates its negative. (We add 1 to avoid negative 0)

;; Convert to conjunctive normal form. props is in internal format.
(define (sudoku-cnf props)
  ;; Each of the following is a list of clauses
  (let ([cell-uniqueness-clauses        ; Every cell has a single digit
         (apply append
                (for*/list ([row (in-range 9)]
                            [col (in-range 9)])
                  (append
                   ;; There is at least one digit in each cell
                   (list (for/list ([digit (in-range 9)])
                           (row-col-digit->prop1 row col digit)))
                   ;; But not more than one
                   (for*/list ([d1 (in-range 9)]
                               [d2 (in-range (+ d1 1) 9)])
                     (list (- (row-col-digit->prop1 row col d1))
                           (- (row-col-digit->prop1 row col d2)))))))]
        [row-completeness-clauses       ; Every row contains all the digits
         (for*/list ([row   (in-range 9)]
                     [digit (in-range 9)])
           (for/list ([col (in-range 9)])
             (row-col-digit->prop1 row col digit)))]
        [column-completeness-clauses    ; Every column contains all the digits
         (for*/list ([col   (in-range 9)]
                     [digit (in-range 9)])
           (for/list ([row (in-range 9)])
             (row-col-digit->prop1 row col digit)))]
        [mini-grid-completeness-clauses ; Every 3x3 subgrid contains all the digits
         (apply append
                (for*/list ([big-row (in-range 3)]
                            [big-col (in-range 3)])
                  (for/list ([digit (in-range 9)])
                    (for*/list ([row (in-range 3)]
                                [col (in-range 3)])
                      (row-col-digit->prop1 (+ (* 3 big-row) row) (+ (* 3 big-col) col) digit)))))])
    ;; Concatenate all the clauses together
    (append
     (map list props)
     ;; (map (λ (p) (list (+ p 1))) props) ; Convert to "external" format
     cell-uniqueness-clauses
     row-completeness-clauses
     column-completeness-clauses
     mini-grid-completeness-clauses)))

(define (row-col-digit->prop1 row col digit)
  (+ (* 81 row) (* 9 col) digit 1))

;; read-puzzle : port? -> (list-of? integer?)
(define (read-puzzle in)
  ;; Proposition is in internal format: 81 x row + 9 x col + digit (Note the +1!)
  ;; Says that digit is in row, col
  (let-values ([(_ digits)
                (for/fold ([pos            0]
                           [known-digits '()])
                          ([ch (in-input-port-chars in)])
                  (cond
                    [(char=? ch #\. )
                     (values (+ pos 1) known-digits)]
                    [(char-numeric? ch)
                     (let ([prop (+ (char-to-digit ch)
                                    (* 9 pos))])
                       (values (+ pos 1)
                               (cons prop known-digits)))]
                    [else
                     (values pos known-digits)]))])
    digits))

;; Emit puzzle to standard out in DIMACS form
;; the propositions must be in external format (starting at 1)
(define (write-cnf-as-dimacs clauses)
  (displayln "c File generated by sudoku.rkt")
  (displayln (format "p cnf ~a ~a" (* 9 9 9) (length clauses)))
  (for ([clause (in-list clauses)])
    (displayln (string-join (map number->string clause) #:after-last " 0"))))


;; props is in internal format: starting at zero
(define (puzzle-format props)
  (let ([posv (make-vector 81 #\.)])
    (for ([d (in-list props)])
      (let* ([row (quotient d 81)]
             [col (quotient (remainder d 81) 9)]
             [num (modulo d 9)])
        (vector-set! posv (+ (* row 9) col) (digit-to-char num))))
    (let ([chars 
           (splice-every-three
            (list #\- #\- #\- #\+ #\- #\- #\- #\+ #\- #\- #\-)
            (for/list ([row (in-range 9)])
              (splice-every-three
               #\|
               (for/list ([col (in-range 9)])
                 (vector-ref posv (+ (* row 9) col))))))])
      (string-join
       (map (λ (row) (string-append (list->string row) "\n")) chars))

      )))

(define (splice-every-three x lst)
  (apply append (add-between (windows 3 3 lst) (list x))))

(define (char-to-digit ch)
  (- (char->integer ch) (char->integer #\0)))

(define (digit-to-char d)
  (integer->char (+ d (char->integer #\0))))

;; ---------------------------------------------------------------------------------------------------
;; 

;; Read kissat solution and return props
;; Assumes that the file is:
;; s SATISFIABLE
;; v m n o ...
;; ...
;; v p q r ... 0
(define (read-kissat in)
  (let* ([ins (string-split (port->string in))]
         [vals (filter-map (λ (val) (if ((or/c "s" "SATISIABLE" "v" "0") val) #f (string->number val))) ins)]
         [props (filter-map (λ (v) (and (> v 0) (- v 1))) vals)])
    props))




;; ---------------------------------------------------------------------------------------------------
;; testing
(module+ test

  ;; From The Guardian, 5 February 2026
  (define puzzle #<<EOS
...|...|...
...|.53|.24
...|24.|57.
---|---|---
..3|...|.9.
.79|..5|.8.
.1.|.7.|..6
---|---|---
..7|...|3..
.41|38.|..7
.6.|..4|.1.
EOS
    )

  (with-output-to-file
    "guardian.cnf"
    (λ ()
      (let* ([props (call-with-input-string puzzle read-puzzle)]
             [cnf   (sudoku-cnf props)])
        (write-cnf-as-dimacs cnf)))
    #:exists 'replace)

  ;; Now at the shell do `kissat -q guardian.cnf > guardian.soln`


  
  (display
   (puzzle-format
    (call-with-input-file
      "guardian.soln"
      read-kissat)))
  
  )
